[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "replicate"
version = "0.7.0"
description = "Python client for Replicate"
readme = "README.md"
license = { file = "LICENSE" }
authors = [{ name = "Replicate, Inc." }]
requires-python = ">=3.8"
dependencies = ["packaging", "pydantic>1", "requests>2"]
optional-dependencies = { dev = ["black", "pytest", "responses", "ruff"] }

[project.urls]
homepage = "https://replicate.com"
repository = "https://github.com/replicate/replicate-python"

[tool.pytest.ini_options]
testpaths = "tests/"

[tool.ruff]
select = [
    "E",   # pycodestyle error
    "F",   # Pyflakes
    "I",   # isort
    "W",   # pycodestyle warning
    "UP",  # pyupgrade
    "S",   # flake8-bandit
    "BLE", # flake8-blind-except
    "FBT", # flake8-boolean-trap
    "B",   # flake8-bugbear
]
ignore = [
    "E501", # Line too long
    "S113", # Probable use of requests call without timeout
]

[tool.ruff.per-file-ignores]
"tests/*" = ["S101", "S106"]
