name: CI

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    name: "Test Python ${{ matrix.python-version }}"

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt -r requirements-dev.txt .
          yes | python -m mypy --install-types replicate || true

      - name: Lint
        run: |
          python -m mypy replicate
          python -m ruff .
          python -m ruff format --check .
      - name: Test
        run: python -m pytest
