name: Release

on:
  push:
    tags: ["*"]

jobs:
  release:
    runs-on: ubuntu-latest

    name: "Publish to PyPI"
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install pypa/build
        run: python -m pip install build --user
      - name: Build a package
        run: python -m build
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
