name: Release

on:
  push:
    tags: ["*"]

jobs:
  release:
    runs-on: ubuntu-20.04

    name: "Publish to PyPI"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build a package
        run: >-
          python -m
          build
          --sdist
          --outdir dist/
          .
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
