name: Release

on:
  push:
    tags: ["*"]

jobs:
  release:
    runs-on: ubuntu-latest

    name: "Publish to PyPI and update API documentation"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install pypa/build
        run: python -m pip install build --user
      - name: Install pdoc
        run: pip install pdoc3
      - name: Generate API documentation
        run: pdoc --force  -o docs replicate
      - name: Commit and push updated documentation
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add docs/
          git commit -m "Update API documentation"
          git push
      - name: Build a package
        run: python -m build
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
